format = '$all'
add_newline = true

[os]
disabled = true

[directory]
read_only = 'ó°Œ¾ '
home_symbol = '~'
style = 'bold fg:cyan'
read_only_style = 'red'

[directory.substitutions]
"notes" = "ğŸ”» "
"nix-nixos" = "ó±„… nix-nixOS"
"nix-darwin" = "ó±„… nix-darwin"

[c]
symbol = "î˜ "

[conda]
disabled = false
symbol = "ï„Œ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_branch]
symbol = "î‚  "

[git_metrics]
disabled = false
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
conflicted = 'âœ˜'
ahead = 'Â»'
behind = 'Â«'
diverged = 'ï˜ '
up_to_date = 'âœ“'
untracked = 'ó°¼ˆ '
modified = '!'
staged = '[++\($count\)](green)'
renamed = 'ó°·®  '
deleted = 'ó°§§ '

[haskell]
symbol = "ó°²’ "

[hostname]
disabled = false
ssh_symbol = 'ğŸŒ '

[julia]
symbol = "î˜¤ "

[lua]
disabled = false
symbol = 'ğŸŒ™ '

[nix_shell]
disabled = false
symbol = 'ó±„… '
format = 'via [â˜ƒï¸ $state( \($name\))](bold blue) '

[ocaml]
symbol = "ğŸª "

[os.symbols]
Macos = 'ó°€µ '
NixOS = 'ó±„… '

[package]
disabled = true
symbol = 'ó°— '

[php]
disabled = false
symbol = "ğŸ˜ "

[python]
disabled = false
symbol = 'ğŸ '

[rust]
disabled = false
symbol = "ğŸ¦€ "

[custom.obsidian]
symbol = "ğŸ‘¾ "
detect_folders = ['.obsidian']
style = 'bold italic dimmed fg:purple'
format = '[$symbol.obsidian ]($style)'

[custom.blender]
symbol = "ó°‚« "
style = 'bold italic dimmed fg:208'
format = '[$symbol[blender-python]($style) ]($style)'
detect_extensions = ['blend1', 'blend']

# overriding direnv since it didn't work
[direnv]
disabled = false

[custom.drenv]
symbol = '~direnv '
style = 'italic dimmed fg:blue'
format = '[$symbol]($style)'
detect_files = ['.envrc']
detect_extensions = ['envrc']
